=== sbecker11/flock-of-postcards/static_content/jobs/proj-mngr-docx-schema.json
{
    "$schema": "https://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "contactInformation": {
            "type": "string"
        },
        "positionOrProfessionalTitle": {
            "type": "string"
        },
        "professionalSummary": {
            "type": "string"
        },
        "workExperience": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "companyName": {
                        "type": "string"
                    },
                    "location": {
                        "type": "string"
                    },
                    "duration": {
                        "type": "object",
                        "properties": {
                            "start": {
                                "type": "string"
                            },
                            "end": {
                                "type": "string"
                            }
                        },
                        "required": [
                            "end",
                            "start"
                        ]
                    },
                    "positionOrTitle": {
                        "type": "string"
                    },
                    "responsibilities": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "companyName",
                    "duration",
                    "location",
                    "positionOrTitle",
                    "responsibilities"
                ]
            }
        },
        "education": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "institution": {
                        "type": "string"
                    },
                    "degree": {
                        "type": "string"
                    }
                },
                "required": [
                    "degree",
                    "institution"
                ]
            }
        },
        "skills": {
            "type": "string"
        },
        "certifications": {
            "type": "string"
        },
        "publications": {
            "type": "string"
        },
        "patents": {
            "type": "string"
        },
        "websites": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [
        "certifications",
        "contactInformation",
        "education",
        "patents",
        "positionOrProfessionalTitle",
        "professionalSummary",
        "publications",
        "skills",
        "websites",
        "workExperience"
    ]
}

=== sbecker11/flock-of-postcards/modules/jobs/test-files/simple-resume-obj.json
{
    "contactInformation": "My contact information",
    "positionOrProfessionalTitle": "My professional title",
    "professionalSummary": "My professional summary",
    "workExperience": [
        {
            "companyName": "Company Name #1",
            "location": "Location 1",
            "duration": {
                "start": "2018-01-01",
                "end": "2019-01-01"
            },
            "positionOrTitle": "Position or Title",
            "responsibilities": [
                "Responsibility 1",
                "Responsibility 2"
            ]
        },
        {
            "companyName": "Company Name #2",
            "location": "Location 2",
            "duration": {
                "start": "2017-01-01",
                "end": "2018-01-01"
            },
            "positionOrTitle": "Position or Title",
            "responsibilities": [
                "Responsibility 1",
                "Responsibility 2"
            ]
        }
    ],
    "education": [
        {
            "institution": "Institution Name #1",
            "degree": "Degree Name #1"
        },
        {
            "institution": "Institution Name #2",
            "degree": "Degree Name #2"
        }
    ],
    "skills": "Skill 1, Skill 2",
    "certifications": "Certification 1, Certification 2",
    "publications": "Publication 1, Publication 2", 
    "patents": "Patent 1, Patent 2",
    "websites": ["Website 1", "Website 2" ]
}

=== sbecker11/flock-of-postcards/modules/jobs/resume-inputs/legitimate-resume.json
{
    "contactInformation": "Joe Doe - 1234 Main St, San Francisco, CA 94123 - 415-555-1234 -",
    "positionOrProfessionalTitle": "Engineer",
    "professionalSummary": "I know how to spell enginer",
    "workExperience": [
        {
            "companyName": "Apple",
            "location": "Cupertino, CA",
            "duration": {
                "start": "2017-01-01",
                "end": "2020-01-01"
            },
            "positionOrTitle": "Software Engineer",
            "responsibilities": [
                "I wrote code",
                "I tested code",
                "I deployed code"
            ]
        },
        {
            "companyName": "Google",
            "location": "Mountain View, CA",
            "duration": {
                "start": "2015-01-01",
                "end": "2017-01-01"
            },
            "positionOrTitle": "Software Engineer",
            "responsibilities": [
                "I wrote code",
                "I tested code",
                "I deployed code"
            ]
        }
    ],
     "education": [
        {
            "institution": "University of California, Berkeley",
            "degree": "B.S. in Electrical Engineering"
        },
        {
            "institution": "University of California, Berkeley",
            "degree": "M.S. in Electrical Engineering"
        }
    ],
    "skills": "skill1 * skill2 * skill3",
    "certifications": "certification1 * certification2 * certification3",
    "publications": "publication1 * publication2 * publication3",
    "patents": "patent1 * patent2 * patent3",
    "websites": [
        "https://www.google.com",
        "https://www.facebook.com"
    ]
}
